### ISSUE TITLE
Onde ficam os layouts para serem implementados?

### ISSUE THREAD

**Issue by teles** [superoak/desafio-front-qmagico#1]
Fiquei com uma dúvida:
- Onde ficam os layouts que devem ser implementados pelos interessados em clonar o repositório? Devem ser pedidos a parte via email ou algo assim?

PS: Legal a iniciativa!! 
O Qmágico é um grande lugar para se trabalhar, crescer como desenvolvedor, como profissional e pessoa.

**Comment by luizotcarvalho** [comment]
@teles  na descrição diz que "Mandaremos um email para você com o layout, mais detalhes dos requisitos desse desafio e qual o prazo de entrega."

Após se cadastrar no formulário http://www.qmagico.com.br/contato/entre_para_o_time você recebe um email com o layout, requisitos e prazos.

**Comment by teles** [comment]
Valeu, @superoak. 
Minha opinião pessoal que ninguém pediu é que isso limita o teste a pessoas que querem participar do processo seletivo, o que pode ser bom ou ruim. 

Pode ter gente que faz o desafio porque achou legal e essa galera poderia acabar conhecendo e se interessando pelo qmágico.
